export interface GroupDefinition {
  name: string;
  agencies: string[];
}

export const GROUPS_DATA: { [key: string]: string[] } = {
  "ADISTEM": ["ADISTEM"],
  "TRACOMEX": ["TRACOMEX"],
  "MARSH": ["MARSH"],
  "AMDA": ["AMDA"],
  "ACAPULCO": ["DISTRIBUIDORA DE ACAPULCO S.A. DE C.V."],
  "ALICA": ["ALICA AUTOMOTRIZ S.A. DE C.V."],
  "ANDRADE": ["AUTOANGAR S.A. DE C.V."],
  "APSA": ["PRESTIGIO MOTRIZ S.A.P.I. DE C.V."],
  "ARTEC": ["AUTOMOTRIZ DE DURANGO S.A. DE C.V."],
  "AUTO CENTRO": ["AUTO CENTRO DE CELAYA S.A. DE C.V."],
  "AUTO DISTRIBUIDORES": ["AUTO DISTRIBUIDORES DEL CENTRO S.A. DE C.V."],
  "AUTO PRODUCTOS": [
    "AUTO PRODUCTOS BAJA S.A. DE C.V.",
    "AUTO PRODUCTOS DE LA COSTA S.A. DE C.V."
  ],
  "AUTOFIN": ["AUTOS ELEGANTES DE PACHUCA S.A. DE C.V."],
  "AUTOMOTORES DE MEXICO": ["AUTOMOTORES DE MEXICO S.A. DE C.V."],
  "AUTOMOTORES QUERETARO": ["AUTOMOVILES PRO SNOP DE QUERETARO S.A. DE C.V."],
  "AUTOMOTRIZ TAMAULIPAS": ["AUTOMOTRIZ TAMAULIPAS S.A. DE C.V."],
  "AUTOMUNDO": [
    "AUTOMUNDO S.A. DE C.V.",
    "INTERLOMAS MUNDO AUTOMOTRIZ S.A. DE C.V."
  ],
  "AUTOS DEL NORTE": ["AUTOS DEL NORTE S.A. DE C.V."],
  "AUTOS Y CAMIONES SOL": ["AUTOS Y CAMIONES SOL DE MICHOACAN S.A. DE C.V."],
  "AYCSA": ["AUTOMOVILES Y CAMIONES S.A. DE C.V."],
  "BICHARA": ["MIRADOR AUTOMOTRIZ S.A. DE C.V."],
  "BOURS": ["AUTOS Y TRACTORES DE SINALOA S.A DE C.V."],
  "CABORCA": ["CABORCA AUTOMOTRIZ S.A. DE C.V."],
  "CAMARENA": ["CAMARENA AUTOMOTRIZ DE OCCIDENTE S.A. DE C.V."],
  "CAMPA": ["AUTOMOTRIZ CAMPA S.A. DE C.V."],
  "CAR ONE": ["CAR ONE MONTERREY S.A. DE C.V."],
  "CAR ONE DEL GOLFO": ["COMERCIAL AUTOMOTRIZ DE POZA RICA S.A. DE C.V."],
  "CER": [
    "AUTOMAYA S.A. DE C.V.",
    "AUTOMOTRIZ CARIBE S.A. DE C.V.",
    "CHETUMAL AUTOMOTORES S.A. DE C.V."
  ],
  "CEVER": ["AUTO NORD S.A. DE C.V."],
  "CLEBER": ["AUTOCAMIONES DE CHIHUAHUA S.A. DE C.V."],
  "COAHUILA MOTORS": ["COAHUILA MOTORS S.A. DE C.V."],
  "CONTINENTAL": ["CONTINENTAL AUTOMOTRIZ S.A. DE C.V."],
  "DF AUTOMOTRIZ": ["DF AUTOMOTRIZ S.A. DE C.V."],
  "DICAS": ["MERIDIEN S.A. DE C.V."],
  "DIEZ": [
    "DIEZ CORDOBA S.A. DE C.V.",
    "DIEZ DE COATZACOALCOS S.A DE C.V.",
    "DIEZ ORIZABA S.A. DE C.V.",
    "DIEZ VERACRUZ S.A. DE C.V."
  ],
  "FAME": ["FAME AUTOMOTRIZ S.A. DE C.V."],
  "FARRERA": ["AUTOMOTORES ANTEQUERA S.A. DE C.V."],
  "FLOSOL": ["AUTOMOTORES FLOSOL S.A. DE C.V."],
  "FR AUTOMOTRIZ": ["EUROVALLE S.A. DE C.V."],
  "GALOJAL": ["GALOJAL S. DE R.L. DE C.V."],
  "GEMA": ["GEMA PREMIER S.A. DE C.V."],
  "GEPRI": ["GUILLERMO PRIETO Y COMPANIA S.A DE C.V."],
  "GRAN AUTO": ["SONORA AUTOMOTRIZ DE CABORCA S.A DE C.V."],
  "GRUPO MARIN": ["GRUMARMEX AUTOS S.A. DE C.V."],
  "GSAU": ["EUROSTAR BAJIO S.A. DE C.V."],
  "HERRERA": ["EUROFRANCE AUTOS S.A. DE C.V."],
  "KASA": ["AUTOMOVILES KASA VIADUCTO S.A. DE C.V."],
  "MENA": ["STELLA MOTORS S.A DE C.V."],
  "MH AUTOMOTRIZ": ["AUTOMOVILES CGE DE ZACATECAS S.A. DE C.V."],
  "MICHOACAN MOTORS": ["MICHOACAN MOTORS S.A. DE C.V."],
  "MISOL": ["MISOL AUTOMOTRIZ S.A. DE C.V."],
  "MONCLOVA": ["AUTOS MONCLOVA S.A. DE C.V."],
  "MOTORMEXA": [
    "GRUPO MOTORMEXA COLIMA S.A. DE C.V.",
    "GRUPO MOTORMEXA GUADALAJARA S.A. DE C.V."
  ],
  "PALMAS": ["PALMAS AUTOMOTRIZ S.A. DE C.V."],
  "PASA": ["CAMBREV AUTOMOTRIZ S.A. DE C.V."],
  "PIOMIKRON": [
    "AUTOMOTORES DE LEON S.A. DE C.V.",
    "AUTOMOVILES DEL BAJIO CAMPESTRE S.A. DE C.V.",
    "AUTOS FINOS DE IRAPUATO S.A. DE C.V.",
    "ECOBIKE S.A. DE C.V."
  ],
  "PLASENCIA": [
    "NUEVA AUTOMOTRIZ DEL TORO S.A. DE C.V.",
    "VEHICULOS EUROPEOS DE GUADALAJARA S.A. DE C.V."
  ],
  "PREMIER": ["PREMIER AUTOCOUNTRY S.A. DE C.V."],
  "REFRAN": [
    "MEGAMOTORS S.A. DE C.V.",
    "REFRAN AUTOS S. DE R.L. DE C.V."
  ],
  "ROCA": ["ROCA AUTOMOTRIZ VALLARTA S.A. DE C.V."],
  "SABALO": ["SABALO DE XALAPA S.A. DE C.V."],
  "SABINAS": ["AUTOMOTRIZ DE SABINAS S.A. DE C.V."],
  "SADO": ["STELLA AUTOMOTRIZ S.A. DE C.V."],
  "SONI": [
    "AUTOMOTORES PEDREGAL S.A. DE C.V.",
    "CUERNAVACA AUTOMOTRIZ S.A. DE C.V."
  ],
  "SONORENSE": ["AUTOMOTRIZ SONORENSE S.A. DE C.V."],
  "STELLANTIS": ["STELLANTIS"],
  "STELLANTIS FINANCIAL": ["STELLANTIS FINANCIAL"],
  "STELLA DE PUEBLA": ["GRUPO STELLA DE PUEBLA S.A.P.I. DE C.V."],
  "SURMAN": [
    "BC DESERTICA MOTORS S.A. DE C.V.",
    "EURO SURMAN S.A. DE C.V.",
    "EUROSURMAN TEC S.A. DE C.V.",
    "LYON MOTORS S.A. DE C.V."
  ],
  "TORRES AUTOMOTRIZ": ["TORRES AUTOMOTRIZ S.A. DE C.V."],
  "TOXA": ["TOUCHE MOTORS S.A. DE C.V."],
  "VALMUR": ["AUTOMOTRIZ LAGUNERA S.A. DE C.V."],
  "UNIÓN DE CRÉDITO": ["UNIÓN DE CRÉDITO"]
};

export const GROUPS_LIST = Object.keys(GROUPS_DATA).sort();
